### ISSUE TITLE
Add 'consistent-return' ?

### ISSUE THREAD

**Issue by AlfonsoML** [xojs/eslint-config-xo#36]
Finally I'm trying to start to use XO (nice job) and one thing that I've noticed as missing is enforcing the consistent-return rule  
http://eslint.org/docs/rules/consistent-return

What do you think about adding it?

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/eslint-config-xo/commit/970367e7b8bd023302f8d4c0725aa95bd37b1874

Basically the rule was too restrictive, buggy, and naive.
