### ISSUE TITLE
Integration with Code Analysis (Codacy, CodeClimate)

### ISSUE THREAD

**Issue by pedronauck** [xojs/eslint-config-xo#39]
How can I integrates XO with code analysis tools like [CodeClimate](https://codeclimate.com/) or [Codacy](https://www.codacy.com/), based that these tools use the `.eslintrc` to parse your analysis? Any idea?

**Comment by sindresorhus** [comment]
With Codacy it seems you can integrate your own tools: https://support.codacy.com/hc/en-us/articles/207994725-Tool-Developer-Guide But they should really just support some kind of reporting interface, so someone could create a XO reporter for it. You should request that on their support channel.

CodeClimate also supports custom engines, but unclear how it works: https://codeclimate.com/engines/

**Comment by sholladay** [comment]
I don't know about those two specifically, but many services like them support output in a format called JUnit XML.

I would be surprised if someone has not created a JUnit reporter for XO yet, though a quick search didn't turn up anything obvious for me.

References:
 - [JUnit reporter for Mocha](https://github.com/michaelleeallen/mocha-junit-reporter)
 - [People talking about JUnit for AVA](https://github.com/avajs/ava/issues/971#issuecomment-277244720)

I guess [codeclimate-stylelint](https://github.com/gilbarbara/codeclimate-stylelint) is the most relevant engine I see on their list. Not sure why building such a thing is necessary, though. There really should be just a standardized reporter interface, as Sindre said, like JUnit XML.
