### ISSUE TITLE
Add the `padding-line-between-statements` rule

### ISSUE THREAD

**Issue by sindresorhus** [xojs/eslint-config-xo#40]
The rule is quite configurable, so I don't have time right now to decide on all the options.

http://eslint.org/docs/rules/padding-line-between-statements

Suggestions welcome.

**Comment by jacobwarduk** [comment]
I would say enforce padding lines between statements.

**Comment by kevva** [comment]
Yes, but I think we decide on which type of statements we should enforce a line between. I think `multiline-block-like` could be a good start, but will need to try them out a little more.

**Comment by sindresorhus** [comment]
@nikersify That's a solid analysis and makes sense to me. We can go with `After multiline blocks`.
