### ISSUE TITLE
Add prettier-ignore to ignore pattern for capitalized-comments

### ISSUE THREAD

**Issue by gurpreetatwal** [xojs/eslint-config-xo#47]
The `capitalized-comments` rule is currently configured as such

```js
      "capitalized-comments": ["error", "always", {
        "ignorePattern": "pragma|ignore",
        "ignoreInlineComments": true,
        "ignoreConsecutiveComments": true
      }]
```

This ends up forcing the `// prettier-ignore` comment to be `// Prettier-ignore` which leads to prettier not ignoring the next line.

**Comment by sindresorhus** [comment]
Sure, PR welcome.
