### ISSUE TITLE
require-await ESLint rule

### ISSUE THREAD

**Issue by EdJoPaTo** [xojs/eslint-config-xo#50]
Is there a reason why the ESLint rule [require-await](https://eslint.org/docs/rules/require-await) is not included but rules like [no-await-in-loop](https://eslint.org/docs/rules/no-await-in-loop) or [no-return-await](https://eslint.org/docs/rules/no-return-await) are?

**Comment by pvdlg** [comment]
I'd be in favor of adding that rule.
@sindresorhus any reason it's not included?
I don't think it should be enabled for a specific version of Node as it applies only for `async` functions which can be used only on compatible Node version anyway.
