### ISSUE TITLE
Consider adding 'avoidEscape: true' to quotes rule

### ISSUE THREAD

**Issue by coreyfarrell** [xojs/eslint-config-xo#51]
I'd like to request that 'avoidEscape: true' be added to the default options for the `quotes` rule.  Prior to ea693f32b4875928d410fbbb208152fb527be3d3 I just used backticks in cases where the string contained single-quotes, but now `const value = 'single-quote \' must be escaped';`.

CC @sindresorhus 

Edit: I'm willing to post a PR for this if acceptable.

**Comment by sindresorhus** [comment]
That change was intentional. I think it's better to always be consistent about quotes and just escape characters when needed.

**Comment by coreyfarrell** [comment]
I understand why allowTemplateLiterals was removed, that change makes sense.  I'm just saying I feel that requiring single-quotes in strings to be escaped is excessive, that is the one time I prefer double-quoted strings in JS.  If you are still against this request we can close this ticket.
