### ISSUE TITLE
Conflict between `no-div-regex` and `no-useless-escape`

### ISSUE THREAD

**Issue by coreyfarrell** [xojs/eslint-config-xo#54]
I have a block of code which uses `str.replace(/=*$/, '')` to on a base64 string (round trip is not needed or wanted, I'm just generating random strings).  First `no-div-regex` complained about this, then I updated the code to `str.replace(/\=*$/, '')` and `no-useless-escape` complained instead.

If you want I can open a bug with eslint, see if they'll add a `ignore-div-regex` boolean option to `no-useless-escape`.  For now I'm just disabling `no-div-regex` on my own repo, leaving it to editors to disambiguate with regex syntax highlighting.

**Comment by sindresorhus** [comment]
> If you want I can open a bug with eslint

👍

**Comment by coreyfarrell** [comment]
I just did an additional test, it appears that `str.replace(/[=]*$/, '')` does not trip either rule and produces the desired result.  I posted eslint/eslint#11355, we'll see if/how they want this handled.
