### ISSUE TITLE
`capitalized-comments` ignore webpack magic comments

### ISSUE THREAD

**Issue by yangmingshan** [xojs/eslint-config-xo#62]
```js
import(
  /* webpackChunkName: "my-chunk-name" */ './some-chunk' // Error: Comments should not begin with a lowercase character
);
```
https://webpack.js.org/api/module-methods/#magic-comments

**Comment by sindresorhus** [comment]
You can add it to https://github.com/xojs/eslint-config-xo/blob/17315d112841b4a2aefa106aa0c34ed2ae0e49da/index.js#L250
