### ISSUE TITLE
Upgrade to `@babel/eslint`

### ISSUE THREAD

**Issue by maicol07** [xojs/eslint-config-xo#72]
`babel-eslint` has been deprecated, in favor of `@babel/eslint`, that is hosted in Babel monorepo. To get recent updates XO config should use the new package

**Comment by sindresorhus** [comment]
I think you opened this in the wrong place. `babel-eslint` is not used here.

**Comment by maicol07** [comment]
> I think you opened this in the wrong place. `babel-eslint` is not used here.

@sindresorhus 😅 you're right! I mean the flow config. Can you transfer this issue to the `eslint-config-flow` repo?

**Comment by sindresorhus** [comment]
I assume you mean, `eslint-config-xo-flow`? I actually don't intend to maintain that repo anymore as it's clear that Flow has no future outside of Facebook.
